//loaders
export const GALLERY_DETAIL_ENABLE_LOADER = 'GALLERY_DETAIL_ENABLE_LOADER';
export const GALLERY_DETAIL_DISABLE_LOADER = 'GALLERY_DETAIL_DISABLE_LOADER';

//image
export const SET_CURRENT_IMAGE_ID = 'SET_CURRENT_IMAGE_ID';
export const GET_IMAGE_DETAIL_REQUEST = 'GET_IMAGE_DETAIL_REQUEST';
export const GET_IMAGE_DETAIL_SUCCESS = 'GET_IMAGE_DETAIL_SUCCESS';
export const GET_IMAGE_DETAIL_FAILED = 'GET_IMAGE_DETAIL_FAILED';
