//loaders
export const GALLERY_LIST_ENABLE_LOADER = 'GALLERY_LIST_ENABLE_LOADER';
export const GALLERY_LIST_DISABLE_LOADER = 'GALLERY_LIST_DISABLE_LOADER';

//images
export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILED = 'GET_IMAGES_FAILED';
